AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Contact form backend for davetashner.com

Globals:
  Function:
    Timeout: 10
    Runtime: nodejs20.x
    MemorySize: 128
    Architectures:
      - arm64

Parameters:
  RecipientEmail:
    Type: String
    Default: davetashner@gmail.com
    Description: Email address to receive contact form submissions
  SenderEmail:
    Type: String
    Default: hello@davetashner.com
    Description: Email address to send from (must be verified in SES)
  AllowedOrigin:
    Type: String
    Default: https://davetashner.com
    Description: Allowed CORS origin
  AlertEmail:
    Type: String
    Default: davetashner@gmail.com
    Description: Email address to receive CloudWatch alerts

Resources:
  ContactFormApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: prod
      CorsConfiguration:
        AllowOrigins:
          - !Ref AllowedOrigin
          - https://www.davetashner.com
        AllowMethods:
          - POST
          - OPTIONS
        AllowHeaders:
          - Content-Type
          - X-Requested-With
        MaxAge: 300

  ContactFormFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: davetashner-contact-form
      CodeUri: contact-handler/
      Handler: index.handler
      Description: Handles contact form submissions from davetashner.com
      Environment:
        Variables:
          RECIPIENT_EMAIL: !Ref RecipientEmail
          SENDER_EMAIL: !Ref SenderEmail
          ALLOWED_ORIGIN: !Ref AllowedOrigin
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - ses:SendEmail
                - ses:SendRawEmail
              Resource: '*'
              Condition:
                StringEquals:
                  ses:FromAddress: !Ref SenderEmail
      Events:
        ContactPost:
          Type: HttpApi
          Properties:
            ApiId: !Ref ContactFormApi
            Path: /contact
            Method: POST

  ContactFormFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${ContactFormFunction}
      RetentionInDays: 14

  # SNS Topic for CloudWatch Alerts
  AlertTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: davetashner-contact-form-alerts
      DisplayName: Contact Form Alerts

  AlertTopicSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref AlertTopic
      Protocol: email
      Endpoint: !Ref AlertEmail

  # CloudWatch Alarm - Lambda Errors
  LambdaErrorsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: davetashner-contact-form-errors
      AlarmDescription: Triggered when Lambda function has errors
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref ContactFormFunction
      AlarmActions:
        - !Ref AlertTopic
      TreatMissingData: notBreaching

  # CloudWatch Alarm - Lambda Throttles
  LambdaThrottlesAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: davetashner-contact-form-throttles
      AlarmDescription: Triggered when Lambda function is throttled
      MetricName: Throttles
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref ContactFormFunction
      AlarmActions:
        - !Ref AlertTopic
      TreatMissingData: notBreaching

  # CloudWatch Alarm - Lambda Duration (80% of 10s timeout = 8000ms)
  LambdaDurationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: davetashner-contact-form-duration
      AlarmDescription: Triggered when Lambda duration exceeds 80% of timeout (8 seconds)
      MetricName: Duration
      Namespace: AWS/Lambda
      Statistic: Average
      Period: 300
      EvaluationPeriods: 1
      Threshold: 8000
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref ContactFormFunction
      AlarmActions:
        - !Ref AlertTopic
      TreatMissingData: notBreaching

  # CloudWatch Dashboard
  ContactFormDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: davetashner-contact-form
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "x": 0,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "title": "Lambda Invocations",
                "region": "${AWS::Region}",
                "metrics": [
                  ["AWS/Lambda", "Invocations", "FunctionName", "${ContactFormFunction}", {"stat": "Sum", "period": 300}]
                ],
                "view": "timeSeries",
                "stacked": false
              }
            },
            {
              "type": "metric",
              "x": 12,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "title": "Lambda Errors",
                "region": "${AWS::Region}",
                "metrics": [
                  ["AWS/Lambda", "Errors", "FunctionName", "${ContactFormFunction}", {"stat": "Sum", "period": 300, "color": "#d62728"}]
                ],
                "view": "timeSeries",
                "stacked": false
              }
            },
            {
              "type": "metric",
              "x": 0,
              "y": 6,
              "width": 12,
              "height": 6,
              "properties": {
                "title": "Lambda Duration (ms)",
                "region": "${AWS::Region}",
                "metrics": [
                  ["AWS/Lambda", "Duration", "FunctionName", "${ContactFormFunction}", {"stat": "Average", "period": 300}],
                  ["...", {"stat": "Maximum", "period": 300}]
                ],
                "view": "timeSeries",
                "stacked": false,
                "annotations": {
                  "horizontal": [
                    {
                      "label": "80% Timeout",
                      "value": 8000,
                      "color": "#ff7f0e"
                    }
                  ]
                }
              }
            },
            {
              "type": "metric",
              "x": 12,
              "y": 6,
              "width": 12,
              "height": 6,
              "properties": {
                "title": "API Gateway Errors",
                "region": "${AWS::Region}",
                "metrics": [
                  ["AWS/ApiGateway", "4xx", "ApiId", "${ContactFormApi}", {"stat": "Sum", "period": 300, "color": "#ff7f0e"}],
                  [".", "5xx", ".", ".", {"stat": "Sum", "period": 300, "color": "#d62728"}]
                ],
                "view": "timeSeries",
                "stacked": false
              }
            }
          ]
        }

Outputs:
  ContactFormApiUrl:
    Description: API Gateway endpoint URL for the contact form
    Value: !Sub 'https://${ContactFormApi}.execute-api.${AWS::Region}.amazonaws.com/prod/contact'
  ContactFormFunctionArn:
    Description: Contact Form Lambda Function ARN
    Value: !GetAtt ContactFormFunction.Arn
  AlertTopicArn:
    Description: SNS Topic ARN for CloudWatch alerts
    Value: !Ref AlertTopic
  DashboardUrl:
    Description: CloudWatch Dashboard URL
    Value: !Sub 'https://${AWS::Region}.console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#dashboards:name=davetashner-contact-form'
